global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'my-app'
    metrics_path: '/actuator/prometheus'  # Your app's metrics endpoint
    static_configs:
      - targets: ['my-app:8080']